### ISSUE TITLE
The connection to the server localhost:8080 was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by nextman786** [hpi-schul-cloud/jitsi-deployment#15]
Hi, I'm trying to get this to run locally but when I run `./kustomize build . | kubectl apply -f -` in the overlays/development folder I get this error: `The connection to the server localhost:8080 was refused - did you specify the right host or port?`

Is there any more setup steps that are not mentioned and required in order to get this project running?

P.S. Thanks a lot for this

**Comment by nextman786** [comment]
No worries, I guess it's not possible at the moment https://github.com/hpi-schul-cloud/jitsi-deployment/issues/13

**Comment by wolfm89** [comment]
This setup is unfortunately not possible to be run locally.
