### ISSUE TITLE
Deployment Fail

### ISSUE THREAD

**Issue by sinuraya** [hpi-schul-cloud/jitsi-deployment#16]
I tried to deploy this services on IONOS kubernete. I deployed scripts in overlays/production using kustomize like your guide in Readme.md. All scripts are executed flawlessly and done. When look into the dashboard, some components are failed to run so they are not available. Kibana is also not available.

My server specification is : 
- xeon 8 cores
- 20 GB Ram
- 600 GB hdd
- 600 GB ssd

**Comment by wolfm89** [comment]
Can you provide more details about what is working and what not?

**Comment by sinuraya** [comment]
Sorry, I already abandon the project, and I didn't make a documentation so I will close this issue. Thank you for the script.
