### ISSUE TITLE
CONNECTION FAILED: connection.otherError 

### ISSUE THREAD

**Issue by amitkverma-1977** [hpi-schul-cloud/jitsi-deployment#17]
Hi ,

Until now this setup used to work perfectly.
Suddenly when I installed afresh the web client is not able to connect. I am seeing this issue in console logs at client.

2020-08-21T09:45:40.193Z [modules/xmpp/xmpp.js] <A.connectionHandler>:  (TIME) Strophe connfail[item-not-found]:	 4319.934999999532
Logger.js:154 2020-08-21T09:45:40.195Z [modules/xmpp/xmpp.js] <A.connectionHandler>:  (TIME) Strophe disconnected[item-not-found]:	 4321.874999999636
Logger.js:154 2020-08-21T09:45:40.196Z [modules/statistics/statistics.js] <Function.S.sendAnalyticsAndLog>:  {"type":"operational","action":"connection.failed","attributes":{"error_type":"connection.otherError","error_message":"item-not-found","suspend_time":0,"time_since_last_success":null}}

app.bundle.min.js?v=4074:126 2020-08-21T09:45:55.578Z [connection.js] <a.u>:  CONNECTION FAILED: connection.otherError

Logger.js:154 2020-08-21T09:46:22.953Z [connection.js] <a.u>:  CONNECTION FAILED: connection.otherError

.....

app.bundle.min.js?v=4074:126 2020-08-21T09:47:55.972Z [connection.js] <a.u>:  CONNECTION FAILED: connection.otherError

UDP ports are open on AWS EC2 instances 

Can you please suggest what could be the reason?

Thanks
Amit

**Comment by wolfm89** [comment]
Where are you running the setup? You're mentioning AWS EC2 but this setup was only tested against Kubernetes in the IONOS cloud. Are you using AWS EKS?
Are the logs you posted from the web container? You need to figure out between what components the connection problems appear.

**Comment by amitkverma-1977** [comment]
I am using AWS EC2 and installing K8s cluster using kops on it. And then installing this setup via kustomize. It works perfectly. Last time it was an issue with AWS UDP ports. Even though all UDP ports were open on AWS but media did not reach the EC2 servers.
I realized that UP ports are required to be opened as soon the cluster is ready and before installing this app. Its wierd but somehow this works for us.
