### ISSUE TITLE
jicofo

### ISSUE THREAD

**Issue by whygodwhy** [hpi-schul-cloud/jitsi-deployment#34]
![image](https://user-images.githubusercontent.com/82667069/115046309-f08e5280-9ef4-11eb-93bc-b73348ef0730.png)
![image](https://user-images.githubusercontent.com/82667069/115046383-04d24f80-9ef5-11eb-8c78-59d78293aa49.png)
### Can You Please Help Me with this issuse
Where I done wrong step.. Please tell me
### Other pods working, but readiness of jicofo not working please help withis issuse
Thank You

**Comment by MatthewPattell** [comment]
@vigneshpalaniappan hi, how you solved this problem? Thanks.
